### ISSUE TITLE
Module docstring for tubes.routing shows old return values

### ISSUE THREAD

**Issue by ralphm** [twisted/tubes#21]
In the pre-move commit twisted/twisted@3877aad93113f01da7cb1e047ca5d4a455131949, the return value for `Router.newRoute` changed so that it no longer returns a tuple of token and fount, but just the fount. The example in the module docstring should be adjusted to reflect this change.

**Comment by glyph** [comment]
Thanks for the report.  Thusly adjusted in 8d1259966e86208238c9c01fc2dcf237d96e0969.
