### ISSUE TITLE
Intro doc appears to suggest that @tube accepts callables. It appears not to

### ISSUE THREAD

**Issue by Julian** [twisted/tubes#67]
The intro doc does things like

```
@tube
def foo(item):
    yield item
```

which presumably would create a simple tube using that function as the `received`, but that does not actually appear to be a thing `tubes.tube.tube` does (and doing so just complains that the resulting object does not have a `started` attribute when you hook it up to a flow).

**Comment by glyph** [comment]
I believe the decorator here is now called `@receiver`?

**Comment by Julian** [comment]
Seems like it.

**Comment by glyph** [comment]
I am fairly sure the doc here has been fixed.

**Comment by glyph** [comment]
(At least, I don't see any misplaced uses of `@tube` on my own.)
