### ISSUE TITLE
Should tubes have gimmicky syntax?

### ISSUE THREAD

**Issue by Julian** [twisted/tubes#71]
tubes.tube.series seems likely to be pretty common.

If you get pretty drunk, does it seem like maybe something like `tube > tube > tube` do `series(tube, tube, tube)`?

**Comment by Julian** [comment]
Er, I guess even besides the recoil, this wouldn't really be too nice if there were multiple different implementations of ITube, you'd really only be able to do it if you had e.g. #73 and shoved __gt__ on that class.

**Comment by Julian** [comment]
Given that #73 is closed, I don't think this is really even doable.

**Comment by glyph** [comment]
welllll you could `tube >> tube >> tube >> cout` if you had some kind of terminal-drain object that implemented the appropriate overloading.  but I'm not going to reopen this myself :)
