### ISSUE TITLE
strports for protocols?

### ISSUE THREAD

**Issue by Julian** [twisted/tubes#72]
(I remember somewhere this idea being brought up but don't remember where that was)

It seems like it might be nice to -- just like endpoints do so for listening+connecting -- have injectable ways of describing what framing is being used on those endpoints, whether it belongs in tubes or otherwise.

E.g., if I decide to run a server using line-delimited messages for testing, I'd like to write something like `line:(stdio:):line` to get a series that does `bytesToLines -> something -> linesToBytes` and then maybe later when I go to prod decide I want `int32netstring:(stdio:):line` because now there's a server on the other end.

Thoughts?

**Comment by glyph** [comment]
If this is a good idea (which, at this point, I sort of doubt) it's pretty low-priority.

**Comment by Julian** [comment]
Fair enough, I don't think I want to really argue for ideas that don't seem good or important :), closing.
