### ISSUE TITLE
Add a helper for connecting a series

### ISSUE THREAD

**Issue by Julian** [twisted/tubes#74]
It seems a bit tedious (and procedural)  to need to write

``` 
def connectStuff(flow):
    flow.fount.flowTo(stuff).flowTo(flow.fount.drain)
```
 
Specifically if I already have a series and just want to listen and flow through that series, rather than just passing that series in somewhere (to a Listener?) I have to manually rig it up as above. Is this not common enough to automate?

(If such a thing already exists maybe this is another doc request)

**Comment by glyph** [comment]
There is nothing that automates this, but I'm also not exactly sure what "this" is.  I think maybe there's no automation because "stuff" typically needs to be constructed per-fount... but OTOH that just means it's `stuff()` and not `stuff`.

Could you expand on the use-case a little?

**Comment by glyph** [comment]
Since I'm not sure how this is actionable, I'm going to close it. But feel free to reopen!

**Comment by Julian** [comment]
I don't remember what the context was here originally, but re-reading my own comment I suspect it was just "I have a `series` and I want to flow data through it" -- I think every program I've tried to write with tubes probably looked like that in one way or another.

Think I was just complaining about having to write the additional flow-connecting boilerplate rather than just having a helper that handled the details of flow connection.
