### ISSUE TITLE
Intro docs: WTF is "flow"

### ISSUE THREAD

**Issue by wsanchez** [twisted/tubes#75]
In the intro docs, under "[Getting Connected: an Echo Server](https://tubes.readthedocs.io/en/latest/tube.html#getting-connected-an-echo-server)", after the example, which looks like this:

```python
def echoFlow(flow):
    flow.fount.flowTo(flow.drain)
```

the next paragraph makes the **outrageous** claim that "In the above example, echoFlow takes two things".  **IT TAKES ONE THING**, or I'm insane (I'm going to assume the former).

I get stuck here wondering if I can't count, and then when I accept that I'm simply being misled, I'm left wondering the degree to which this evil plot to confuse me is trying to drive me nuts, which them makes me wonder if perhaps I'm already nuts, and I should have assumed the latter.

**WTF is flow?**  Is it a type I should know about?  Or some random thingo with these two attributes attached to it?  **OMG I DON'T KNOW!**  And then it says here that **the function** is a "flow".  **WHAT?!?  Why is the argument called the thing that the function is?**

Anyway, I feel like I'd be feeling a lot less stress if this function actually took two arguments:

```python
def echoFlow(fount, drain):
    fount.flowTo(drain)
```

Then you can say it takes two thing, and even call the function a flow and I'd be cool with all of that.

Peace be unto you.

**Comment by glyph** [comment]
https://twisted.github.io/tubes/docs/tubes.listening.Flow.html

**Comment by glyph** [comment]
Originally this was a 2-tuple of `fount` / `drain` which is why it says "two things".

**Comment by glyph** [comment]
(It should be fixed. It's one thing.)
