### ISSUE TITLE
Setuptools warnings detected for newer python versions, python-3.8, 3.9

### ISSUE THREAD

**Issue by dol-sen** [twisted/tubes#88]
build log snipits:

writing manifest file 'Tubes.egg-info/SOURCES.txt'
/usr/lib/python3.8/site-packages/setuptools/dist.py:153: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")
...
running install_scripts
/usr/lib/python3.8/site-packages/setuptools/dist.py:153: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")
...
writing Tubes.egg-info/PKG-INFO
/usr/lib/python3.9/site-packages/setuptools/dist.py:153: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")
writing dependency_links to Tubes.egg-info/dependency_links.txt
writing requirements to Tubes.egg-info/requires.txt
writing top-level names to Tubes.egg-info/top_level.txt
...
running install_egg_info
running egg_info
writing Tubes.egg-info/PKG-INFO
/usr/lib/python3.9/site-packages/setuptools/dist.py:153: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")

##########

Full build logs available at Gentoo's Bugzilla

https://bugs.gentoo.org/797271
https://bugs.gentoo.org/attachment.cgi?id=717297

**Comment by dol-sen** [comment]
googling the error, I found this link: https://github.com/pypa/setuptools/issues/1390

So, the warning may be due to:
    description="""
    Flow control and backpressure for event-driven applications.
    """,

**Comment by webknjaz** [comment]
@dol-sen I'm about to send a PR to the setuptools upstream turning that warning into an exception. Just a heads up in case you want to fix this here.

**Comment by dol-sen** [comment]
Thank you

**Comment by graingert** [comment]
@webknjaz thanks for the bump! I've got a PR to fix this

while waiting for a release of tubes, I don't think setuptools removing this feature will pose a problem to Tubes users because pypi has Tubes-0.2.0-py2.py3-none-any.whl so anyone with a new enough setuptools probably also has a new enough pip to get the wheel.
