### ISSUE TITLE
switch to github actions

### ISSUE THREAD

**Issue by glyph** [twisted/tubes#90]
travis-ci obviously isn't actually running the tests any more

**Comment by Damola12345** [comment]
hi @glyph can i help out with the switch to github actions?

**Comment by glyph** [comment]
@Damola12345 Absolutely! Can you do a quick PR?

**Comment by Damola12345** [comment]
@glyph  okay

**Comment by glyph** [comment]
@Damola12345 Thanks for kicking this off. I had to bash the workflow a bit and fix some bitrot in our build but we now have working CI again.

**Comment by Damola12345** [comment]
@glyph your welcome 
if you have any devops related task you can assign to me 
will love to work on them
